---
- name: deployment of SP GATEKEEPER as a Docker containers from Registry
  hosts: target
  sudo: yes
  tasks:

  # Running the Sonata GK Docker Images

  - name: GATEKEEPER GUI - running Docker containers
    docker_container:
      name: son-gui
      image: sonatanfv/son-gui
 #     debug: msg="The IP is{{ inventory_hostname }}"
      env:
        MON_URL: "{{ inventory_hostname }}:8000"
        GK_URL: "{{ inventory_hostname }}:32001"
        LOGS_URL: "{{ inventory_hostname }}:12900"
      state: started
      exposed_ports: 80
      ports: "80:80"

  - name: GATEKEEPER BSS - running Docker containers
    docker:
      name: son-bss
      image: sonatanfv/son-yo-gen-bss
      command: grunt serve:integration --gkApiUrl=http://{{ inventory_hostname }}:32001
      state: started
      ports: "25001:1337"

  - name: GATEKEEPER PACKAGES - running Docker containers
    docker_container:
      name: son-gtkpkg
      image: sonatanfv/son-gtkpkg
      env:
        CATALOGUES_URL: http://{{ inventory_hostname }}:4002/catalogues
        RACK_ENV: integration
      state: started
      ports: "5100:5100"

  - name: GATEKEEPER SERVER - running Docker containers
    docker_container:
      name: son-gtksrv
      image: sonatanfv/son-gtksrv
      env:
        CATALOGUES_URL: http://{{ inventory_hostname }}:4002/catalogues
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ inventory_hostname }}:5672
        DATABASE_HOST: "{{ inventory_hostname }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
      links:
        - son-broker
      state: started
      ports: "5300:5300"

  - name: GATEKEEPER FUNCTIONS - running Docker containers
    docker_container:
      name: son-gtkfnct
      image: sonatanfv/son-gtkfnct
      env:
        CATALOGUES_URL: http://{{ inventory_hostname }}:4002/catalogues
        RACK_ENV: integration
      state: started
      ports: "5500:5500"

  - name: GATEKEEPER RECORDS - running Docker containers
    docker_container:
      name: son-gtkrec
      image: sonatanfv/son-gtkrec
      env:
        REPOSITORIES_URL: http://{{ inventory_hostname }}:4002/records
        RACK_ENV: integration
      state: started
      ports: "5800:5800"

  - name: GATEKEEPER VIM - running Docker containers
    docker_container:
      name: son-gtkvim
      image: sonatanfv/son-gtkvim
      env:
        RACK_ENV: integration
        MQSERVER: amqp://guest:guest@{{ inventory_hostname }}:5672
        DATABASE_HOST: "{{ inventory_hostname }}"
        DATABASE_PORT: 5432
        POSTGRES_PASSWORD: sonata
        POSTGRES_USER: sonatatest
      links:
        - son-broker
      state: started
      ports: "5700:5700"

  - name: GATEKEEPER API - running Docker containers
    docker_container:
      name: son-gtkapi
      image: sonatanfv/son-gtkapi
      env:
        RACK_ENV: integration
        PACKAGE_MANAGEMENT_URL: http://{{ inventory_hostname }}:5100
        SERVICE_MANAGEMENT_URL: http://{{ inventory_hostname }}:5300
        FUNCTION_MANAGEMENT_URL: http://{{ inventory_hostname }}:5500
        VIM_MANAGEMENT_URL: http://{{ inventory_hostname }}:5700 
        RECORD_MANAGEMENT_URL: http://{{ inventory_hostname }}:5800
      links:
        - son-gtkpkg
        - son-gtkfnct
        - son-gtkrec
        - son-gtksrv
        - son-gtkvim
      state: started
      ports: "32001:5000"
